// config actions
export const CONFIGS_INIT = 'CONFIGS_INIT'
export const CONFIGS_DIRECT_RESET = 'CONFIGS_DIRECT_RESET'
export const CONFIGS_ACTION_RESET = 'CONFIGS_ACTION_RESET'
export const CONFIGS_INIT_MOBILE = 'CONFIGS_INIT_MOBILE'
export const CONFIGS_SET_MOBILE = 'CONFIGS_SET_MOBILE'
export const ERROR_OPEN_API_ERRORS = 'ERROR_OPEN_API_ERRORS'

// TOP画面の見積連番一覧POP
export const TOP_MITUMORI_OPEN = 'TOP_MITUMORI_OPEN'
export const TOP_MITUMORI_CLOSE = 'TOP_MITUMORI_CLOSE'

export const CONFIGS_LOAD_COOKIE = 'CONFIGS_LOAD_COOKIE'
export const READ_NOTICE_LIST = 'READ_NOTICE_LIST'
export const READ_ENTRY_NO_LIST = 'READ_ENTRY_NO_LIST'

export const FILE_UPLOAD = 'FILE_UPLOAD'
export const ACTIONS = {
  // config
  CONFIGS_INIT,
  CONFIGS_DIRECT_RESET,
  CONFIGS_ACTION_RESET,
  CONFIGS_INIT_MOBILE,
  CONFIGS_SET_MOBILE,
  CONFIGS_LOAD_COOKIE,
  // TOP
  TOP_MITUMORI_OPEN,
  TOP_MITUMORI_CLOSE,
  FILE_UPLOAD,
  // ERROR
  ERROR_OPEN_API_ERRORS
}
