// config actions
export const CONFIGS_INIT = 'CONFIGS_INIT'
export const CONFIGS_DIRECT_RESET = 'CONFIGS_DIRECT_RESET'
export const CONFIGS_ACTION_RESET = 'CONFIGS_ACTION_RESET'
export const CONFIGS_INIT_MOBILE = 'CONFIGS_INIT_MOBILE'
export const CONFIGS_SET_MOBILE = 'CONFIGS_SET_MOBILE'

// TOP画面の見積連番一覧POP
export const TOP_MITUMORI_OPEN = 'TOP_MITUMORI_OPEN'
export const TOP_MITUMORI_CLOSE = 'TOP_MITUMORI_CLOSE'

export const CONFIGS_LOAD_COOKIE = 'CONFIGS_LOAD_COOKIE'
export const READ_NOTICE_LIST = 'READ_NOTICE_LIST'
export const READ_ENTRY_NO_LIST = 'READ_ENTRY_NO_LIST'
// 見積連番一覧
export const MYAPP_READ_ENTRY_NO_LIST = 'MYAPP_READ_ENTRY_NO_LIST'
export const MYAPP_SET_ENTRY_NO = 'MYAPP_SET_ENTRY_NO'

// home assist actions
export const MYAPP_CLEAR = 'MYAPP_CLEAR'
export const MYAPP_SAVE = 'MYAPP_SAVE'

// home assist server actions
export const MYAPP_SVR_CHECK = 'MYAPP_SVR_CHECK'
export const MYAPP_SVR_ENTRY_LOAD = 'MYAPP_SVR_ENTRY_LOAD'
export const MYAPP_SVR_ENTRY_SAVE = 'MYAPP_SVR_ENTRY_SAVE'
export const MYAPP_SVR_CONFIRM_FEE = 'MYAPP_SVR_CONFIRM_FEE'
export const MYAPP_SVR_REQUEST_REVIEW = 'MYAPP_SVR_REQUEST_REVIEW'
export const MYAPP_SVR_FILE_UPLOAD = 'MYAPP_SVR_FILE_UPLOAD'
export const MYAPP_SVR_FILE_DELETE = 'MYAPP_SVR_FILE_DELETE'
export const MYAPP_SVR_FILE_DELETE_ARRAY = 'MYAPP_SVR_FILE_DELETE_ARRAY'
export const MYAPP_SVR_ESTIMATED = 'MYAPP_SVR_ESTIMATED'
export const MYAPP_SVR_ADD_SEARCH = 'MYAPP_SVR_ADD_SEARCH'
export const MYAPP_SVR_CALC_EARTHQUAKE = 'MYAPP_SVR_CALC_EARTHQUAKE'

// プラン設定
export const MYAPP_SET_ESTIMATE_PLAN = 'MYAPP_SET_ESTIMATE_PLAN'

// オプションの設定
export const MYAPP_SET_ESTIMATE_OPTION = 'MYAPP_SET_ESTIMATE_OPTION'

// 年次取得法で保険金額を取得
export const MYAPP_SVR_ACQUISITION_ANNUAL = 'MYAPP_SVR_ACQUISITION_ANNUAL'
// 概観法で保険金額を取得
export const MYAPP_SVR_OVERVIEW = 'MYAPP_SVR_OVERVIEW'
// 概観法で保険金額を取得
export const MYAPP_SVR_HOUSEHOLD_EVOLUTION = 'MYAPP_SVR_HOUSEHOLD_EVOLUTION'
// その他評価法
export const MYAPP_SVR_OTHER_METHOD = 'MYAPP_SVR_OTHER_METHOD'
// 申込依頼
export const MYAPP_SVR_ENTRY_REQUEST = 'MYAPP_SVR_ENTRY_REQUEST'
// 申込登録
export const MYAPP_SVR_ENTRY_REGISTRATION = 'MYAPP_SVR_ENTRY_REGISTRATION'
// 申込依頼NO.再通知
export const MYAPP_SVR_ENTRYNO_REINFORM = 'MYAPP_SVR_ENTRYNO_REINFORM'

// 試算
export const MYAPP_SVR_CALC_ESTIMATE = 'MYAPP_SVR_CALC_ESTIMATE'
// 引受制限
export const MYAPP_SVR_ACCEPT_LIMIT_RULE_ADD = 'MYAPP_SVR_ACCEPT_LIMIT_RULE_ADD'
export const MYAPP_SVR_ACCEPT_LIMIT_RULE_REMOVE = 'MYAPP_SVR_ACCEPT_LIMIT_RULE_REMOVE'
export const MYAPP_SVR_ACCEPT_LIMIT_CHECK = 'MYAPP_SVR_ACCEPT_LIMIT_CHECK'
export const MYAPP_SVR_ACCEPT_LIMIT_CACHE_CLEAR = 'MYAPP_SVR_ACCEPT_LIMIT_CACHE_CLEAR'
export const MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_SAVE = 'MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_SAVE'
export const MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_CLEAR = 'MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_CLEAR'

// SMBC
export const SMBC_GET_TOKEN = 'SMBC_GET_TOKEN'
// popup
export const POPUP_OPEN = 'POPUP_OPEN'
export const POPUP_CLOSE = 'POPUP_CLOSE'
export const SET_CONFIRM_IN_POPUP_CLOSE = 'SET_CONFIRM_IN_POPUP_CLOSE'
export const AREAMAP_POPUP = 'AREAMAP_POPUP'
export const HELP_OPEN = 'HELP_OPEN'
export const HELP_CLOSE = 'HELP_CLOSE'
export const DOCUMENT_OPEN = 'DOCUMENT_OPEN'
export const DOCUMENT_CLOSE = 'DOCUMENT_CLOSE'
// エラーpopup
export const ERROR_OPEN = 'ERROR_OPEN'
export const ERROR_OPEN_CONFIRM = 'ERROR_OPEN_CONFIRM'
export const ERROR_CLOSE = 'ERROR_CLOSE'
export const ERROR_CLOSE_CONFIRM = 'ERROR_CLOSE_CONFIRM'
export const ERROR_OPEN_API_ERRORS = 'ERROR_OPEN_API_ERRORS'

// 地震保険の調査情報（加入率）
export const EARTHQUAKE_SUBSCRIBER = 'EARTHQUAKE_SUBSCRIBER'

// Loading
export const LOADING_ON = 'LOADING_ON'
export const LOADING_OFF = 'LOADING_OFF'

// マイページAPI
export const MYPAGE_SVR_ACTIVATION = 'MYPAGE_SVR_ACTIVATION'
export const MYPAGE_SVR_UPDATE_MYAPP = 'MYPAGE_SVR_UPDATE_MYAPP'

// 明記物件明細データ取得処理
export const MYAPP_SPECIFICATION_ARTICLE_INPUT_INIT = 'MYAPP_SPECIFICATION_ARTICLE_INPUT_INIT'
// 明記物件明細書入力画面の入力完了
export const MYAPP_SPECIFICATION_ARTICLE_INPUT_COMPLETED = 'MYAPP_SPECIFICATION_ARTICLE_INPUT_COMPLETED'
export const SET_SPECIFICATION_ARTICLE_INPUT_CHANGE_FLAG = 'SET_SPECIFICATION_ARTICLE_INPUT_CHANGE_FLAG'

// 他契約有無確認画面
export const MYAPP_WITH_OTHER_INIT = 'MYAPP_WITH_OTHER_INIT'
export const MYAPP_WITH_OTHER_CONFIRM = 'MYAPP_WITH_OTHER_CONFIRM'
export const SET_CONFIRM_TERM_CLEAR_FLAG = 'SET_CONFIRM_TERM_CLEAR_FLAG'

// 代理店分担入力画面
export const MYAPP_AGENT_SHARE_INPUT_COMPLETED = 'MYAPP_AGENT_SHARE_INPUT_COMPLETED'
export const MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST = 'MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST'
export const MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST_NEW = 'MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST_NEW'
export const MANAGEMENT_GETAGENTNAME = 'MANAGEMENT_GETAGENTNAME'

// 申込依頼画面（口振）
export const MYAPP_ENTRYACCOUNTTRANSFER_GET_API = 'MYAPP_ENTRYACCOUNTTRANSFER_GET_API'
export const MYAPP_ENTRYACCOUNTTRANSFER_GET_API_TEMP = 'MYAPP_ENTRYACCOUNTTRANSFER_GET_API_TEMP'

// G-NHA-010_内容確認画面
export const MYAPP_SEARCH_RECRUITMENT = 'MYAPP_SEARCH_RECRUITMENT'
export const MYAPP_SET_RECRUITMENT_ID = 'MYAPP_SET_RECRUITMENT_ID'

// 有料オプション設定ポップアップ画面（ホームアシスト）
export const MYAPP_ESTIMATE_OPTION_INIT = 'MYAPP_ESTIMATE_OPTION_INIT'
// 申込依頼口振
export const MYAPP_ENTRY_REQUEST_ACCOUNT = 'MYAPP_ENTRY_REQUEST_ACCOUNT'
// 口座検索
export const MYAPP_BANK_SEARCH = 'MYAPP_BANK_SEARCH'
export const MYAPP_GEN_POLICY_NO = 'MYAPP_GEN_POLICY_NO'
export const MYAPP_GEN_PDF = 'MYAPP_GEN_PDF'

// 一時保存（契約者名）
export const MYAPP_CONTRACTORNAME = 'MYAPP_CONTRACTORNAME'

export const ACTIONS = {
  // config
  CONFIGS_INIT,
  CONFIGS_DIRECT_RESET,
  CONFIGS_ACTION_RESET,
  CONFIGS_INIT_MOBILE,
  CONFIGS_SET_MOBILE,
  CONFIGS_LOAD_COOKIE,
  READ_NOTICE_LIST,
  READ_ENTRY_NO_LIST,
  // 見積連番一覧
  MYAPP_READ_ENTRY_NO_LIST,
  MYAPP_SET_ENTRY_NO,
  // TOP
  TOP_MITUMORI_OPEN,
  TOP_MITUMORI_CLOSE,
  // home assist
  MYAPP_CLEAR,
  MYAPP_SAVE,
  MYAPP_SVR_CHECK,
  MYAPP_SVR_ENTRY_LOAD,
  MYAPP_SVR_ENTRY_SAVE,
  MYAPP_SVR_CONFIRM_FEE,
  MYAPP_SVR_REQUEST_REVIEW,
  MYAPP_SVR_FILE_UPLOAD,
  MYAPP_SVR_FILE_DELETE,
  MYAPP_SVR_FILE_DELETE_ARRAY,
  MYAPP_SVR_ENTRY_REQUEST,
  MYAPP_SVR_ENTRY_REGISTRATION,
  MYAPP_SVR_ESTIMATED,
  MYAPP_SVR_ADD_SEARCH,
  MYAPP_SVR_ENTRYNO_REINFORM,
  MYAPP_SVR_CALC_ESTIMATE,
  MYAPP_SVR_CALC_EARTHQUAKE,
  MYAPP_SVR_ACCEPT_LIMIT_RULE_ADD,
  MYAPP_SVR_ACCEPT_LIMIT_RULE_REMOVE,
  MYAPP_SVR_ACCEPT_LIMIT_CHECK,
  MYAPP_SVR_ACCEPT_LIMIT_CACHE_CLEAR,
  MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_SAVE,
  MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_CLEAR,
  SMBC_GET_TOKEN,
  MYAPP_SVR_OTHER_METHOD,
  // プラン設定
  MYAPP_SET_ESTIMATE_PLAN,
  // フリープランオプション設定
  MYAPP_SET_ESTIMATE_OPTION,
  // 評価法
  MYAPP_SVR_ACQUISITION_ANNUAL,
  MYAPP_SVR_OVERVIEW,
  // 家財評価額
  MYAPP_SVR_HOUSEHOLD_EVOLUTION,
  // popup
  POPUP_OPEN,
  POPUP_CLOSE,
  SET_CONFIRM_IN_POPUP_CLOSE,
  HELP_OPEN,
  HELP_CLOSE,
  AREAMAP_POPUP,
  DOCUMENT_OPEN,
  DOCUMENT_CLOSE,
  // エラーpopup
  ERROR_OPEN,
  ERROR_OPEN_CONFIRM,
  ERROR_CLOSE,
  ERROR_CLOSE_CONFIRM,
  ERROR_OPEN_API_ERRORS,
  // 地震保険の調査情報（加入率）
  EARTHQUAKE_SUBSCRIBER,
  // Loading
  LOADING_ON,
  LOADING_OFF,
  // マイページAPI
  MYPAGE_SVR_ACTIVATION,
  MYPAGE_SVR_UPDATE_MYAPP,
  // 明記物件明細書入力画面
  MYAPP_SPECIFICATION_ARTICLE_INPUT_INIT,
  MYAPP_SPECIFICATION_ARTICLE_INPUT_COMPLETED,
  SET_SPECIFICATION_ARTICLE_INPUT_CHANGE_FLAG,
  // 他契約有無確認画面
  MYAPP_WITH_OTHER_INIT,
  MYAPP_WITH_OTHER_CONFIRM,
  SET_CONFIRM_TERM_CLEAR_FLAG,

  // 代理店分担入力画面
  MYAPP_AGENT_SHARE_INPUT_COMPLETED,
  MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST,
  MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST_NEW,
  MANAGEMENT_GETAGENTNAME,

  // 申込依頼画面（口振）
  MYAPP_ENTRYACCOUNTTRANSFER_GET_API,
  MYAPP_ENTRYACCOUNTTRANSFER_GET_API_TEMP,

  // G-NHA-010_内容確認画面
  MYAPP_SEARCH_RECRUITMENT,
  MYAPP_SET_RECRUITMENT_ID,

  // 有料オプション設定ポップアップ画面（ホームアシスト）
  MYAPP_ESTIMATE_OPTION_INIT,

  // 申込依頼口振
  MYAPP_ENTRY_REQUEST_ACCOUNT,
  // 口座検索
  MYAPP_BANK_SEARCH,
  MYAPP_GEN_POLICY_NO,
  MYAPP_GEN_PDF,
  // 一時保存（契約者名）
  MYAPP_CONTRACTORNAME
}
