// config mutations
export const CONFIGS_INIT = 'CONFIGS_INIT'
export const CONFIGS_DIRECT_RESET = 'CONFIGS_DIRECT_RESET'
export const CONFIGS_ACTION_RESET = 'CONFIGS_ACTION_RESET'
export const CONFIGS_CHANGE_MOBILE = 'CONFIGS_CHANGE_MOBILE'

export const CONFIGS_SET_COOKIE = 'CONFIGS_SET_COOKIE'
export const READ_NOTICE_LIST = 'READ_NOTICE_LIST'
export const READ_ENTRY_NO_LIST = 'READ_ENTRY_NO_LIST'
export const CLEAR_ENTRY_NO_LIST = 'CLEAR_ENTRY_NO_LIST'

// TOP画面の見積連番一覧POP
export const UI_SET_TOP_MITUMORI = 'UI_SET_TOP_MITUMORI'
export const FILE_UPLOAD = 'FILE_UPLOAD'
// APP
export const MYAPP_SET_SYNC = 'MYAPP_SET_SYNC'
export const MYAPP_USER_LOGIN_OK = 'MYAPP_USER_LOGIN_OK'
export const MYAPP_USER_KANRI_OK = 'MYAPP_USER_KANRI_OK'
export const MYAPP_USER_CREATE_OK = 'MYAPP_USER_CREATE_OK'
export const MYAPP_USER_INSERT_OK = 'MYAPP_USER_INSERT_OK'
export const MYAPP_USER_DELETE_OK = 'MYAPP_USER_DELETE_OK'
export const MYAPP_USER_ALBUM_OK = 'MYAPP_USER_ALBUM_OK'
export const MYAPP_ALBUMCREATE_OK = 'MYAPP_ALBUMCREATE_OK'
export const MYAPP_ALBUM_REMOVE_OK = 'MYAPP_ALBUM_REMOVE_OK'
export const MYAPP_ALBUM_DOMAIN_OK = 'MYAPP_ALBUM_DOMAIN_OK'
export const MYAPP_USER_RIYO_OK = 'MYAPP_USER_RIYO_OK'
export const MYAPP_USER_RIYOEFF_OK = 'MYAPP_USER_RIYOEFF_OK'
export const MYAPP_USER_INFO_OK = 'MYAPP_USER_INFO_OK'
export const MYAPP_ALBUM_IMAGES_OK = 'MYAPP_ALBUM_IMAGES_OK'
export const MYAPP_IMAGES_SETSUMEI_OK = 'MYAPP_IMAGES_SETSUMEI_OK'
export const MYAPP_USER_KENGEN_OK = 'MYAPP_USER_KENGEN_OK'
export const MYAPP_CONTRACT_LIST_OK = 'MYAPP_CONTRACT_LIST_OK'
export const MYAPP_CONTRACT_GET_OK = 'MYAPP_CONTRACT_GET_OK'
export const MYAPP_CONTRACT_ADD_OK = 'MYAPP_CONTRACT_ADD_OK'
export const MYAPP_CONTRACT_EDIT_OK = 'MYAPP_CONTRACT_EDIT_OK'
export const MYAPP_CONTRACT_REMOVE_OK = 'MYAPP_CONTRACT_REMOVE_OK'

export const MUTATIONS = {
  // config
  CONFIGS_INIT,
  CONFIGS_DIRECT_RESET,
  CONFIGS_ACTION_RESET,
  CONFIGS_CHANGE_MOBILE,
  CONFIGS_SET_COOKIE,
  READ_NOTICE_LIST,
  READ_ENTRY_NO_LIST,
  CLEAR_ENTRY_NO_LIST,
  // TOP画面の見積連番一覧POP
  UI_SET_TOP_MITUMORI,
  FILE_UPLOAD,
  // APP
  MYAPP_SET_SYNC,
  MYAPP_USER_LOGIN_OK,
  MYAPP_USER_KANRI_OK,
  MYAPP_USER_CREATE_OK,
  MYAPP_USER_INSERT_OK,
  MYAPP_USER_DELETE_OK,
  MYAPP_USER_ALBUM_OK,
  MYAPP_USER_RIYO_OK,
  MYAPP_ALBUM_REMOVE_OK,
  MYAPP_ALBUM_DOMAIN_OK,
  MYAPP_ALBUMCREATE_OK,
  MYAPP_USER_RIYOEFF_OK,
  MYAPP_USER_INFO_OK,
  MYAPP_ALBUM_IMAGES_OK,
  MYAPP_IMAGES_SETSUMEI_OK,
  MYAPP_USER_KENGEN_OK,
  MYAPP_CONTRACT_LIST_OK,
  MYAPP_CONTRACT_GET_OK,
  MYAPP_CONTRACT_ADD_OK,
  MYAPP_CONTRACT_EDIT_OK,
  MYAPP_CONTRACT_REMOVE_OK
}
