// config mutations
export const CONFIGS_INIT = 'CONFIGS_INIT'
export const CONFIGS_DIRECT_RESET = 'CONFIGS_DIRECT_RESET'
export const CONFIGS_ACTION_RESET = 'CONFIGS_ACTION_RESET'
export const CONFIGS_CHANGE_MOBILE = 'CONFIGS_CHANGE_MOBILE'

export const CONFIGS_SET_COOKIE = 'CONFIGS_SET_COOKIE'
export const READ_NOTICE_LIST = 'READ_NOTICE_LIST'
export const READ_ENTRY_NO_LIST = 'READ_ENTRY_NO_LIST'
export const CLEAR_ENTRY_NO_LIST = 'CLEAR_ENTRY_NO_LIST'
// 見積連番一覧
export const MYAPP_READ_ENTRY_NO_LIST = 'MYAPP_READ_ENTRY_NO_LIST'
export const MYAPP_SET_ENTRY_NO = 'MYAPP_SET_ENTRY_NO'

// TOP画面の見積連番一覧POP
export const UI_SET_TOP_MITUMORI = 'UI_SET_TOP_MITUMORI'

// ui mutations
export const UI_SET_POPUP = 'UI_SET_POPUP'
export const UI_SET_CONFIRM_IN_POPUP_CLOSE = 'UI_SET_CONFIRM_IN_POPUP_CLOSE'
export const UI_SET_HELP = 'UI_SET_HELP'
export const UI_SET_DOCUMENT = 'UI_SET_DOCUMENT'

// errors mutations
export const ERROR_UI_SET_POPUP = 'ERROR_UI_SET_POPUP'
export const ERROR_UI_SET_POPUP_CONFIRM = 'ERROR_UI_SET_POPUP_CONFIRM'
export const ERROR_UI_UNSET_POPUP_CONFIRM = 'ERROR_UI_UNSET_POPUP_CONFIRM'

// home assist mutations
export const MYAPP_SET_SYNC = 'MYAPP_SET_SYNC'
export const MYAPP_SET_ENTRY_TYPE = 'MYAPP_SET_ENTRY_TYPE'
export const MYAPP_SET_POLICY_NO = 'MYAPP_SET_POLICY_NO'
export const MYAPP_SET_DATA = 'MYAPP_SET_DATA'
export const MYAPP_SET_BEFORE_CORRECTION = 'MYAPP_SET_BEFORE_CORRECTION'
export const MYAPP_SET_DATA_APPRAISAL = 'MYAPP_SET_DATA_APPRAISAL'
export const MYAPP_SET_UPLOAD_FILE_INFO = 'MYAPP_SET_UPLOAD_FILE_INFO'
export const MYAPP_SET_ALERT_INFO = 'MYAPP_SET_ALERT_INFO'
export const MYAPP_SET_ESTIMATEDDATA = 'MYAPP_SET_ESTIMATEDDATA'
export const MYAPP_SET_ADDRESSDATA = 'MYAPP_SET_ADDRESSDATA'
export const MYAPP_CLEAR_DATA = 'MYAPP_CLEAR_DATA'

// 年次取得法で保険金額を取得
export const MYAPP_SVR_ACQUISITION_ANNUAL = 'MYAPP_SVR_ACQUISITION_ANNUAL'
// 概観法で保険金額を取得
export const MYAPP_SVR_OVERVIEW = 'MYAPP_SVR_OVERVIEW'
// 家財評価額算出
export const MYAPP_SVR_HOUSEHOLD_EVOLUTION = 'MYAPP_SVR_HOUSEHOLD_EVOLUTION'

// 試算結果
export const MYAPP_SET_ESTIMATE = 'MYAPP_SET_ESTIMATE'
// 引受制限
export const MYAPP_SVR_ACCEPT_LIMIT_RULE_ADD = 'MYAPP_SVR_ACCEPT_LIMIT_RULE_ADD'
export const MYAPP_SVR_ACCEPT_LIMIT_RULE_REMOVE = 'MYAPP_SVR_ACCEPT_LIMIT_RULE_REMOVE'
export const MYAPP_SVR_ACCEPT_LIMIT_CHECK = 'MYAPP_SVR_ACCEPT_LIMIT_CHECK'
export const MYAPP_SVR_ACCEPT_LIMIT_CACHE_CLEAR = 'MYAPP_SVR_ACCEPT_LIMIT_CACHE_CLEAR'
export const MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_SAVE = 'MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_SAVE'
export const MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_CLEAR = 'MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_CLEAR'

// 代理店分担入力表示フラグを設定
export const MYAPP_SET_SHOW_AGENTSHAREINPUT = 'MYAPP_SET_SHOW_AGENTSHAREINPUT'

// SMBC
export const SMBC_GET_TOKEN = 'SMBC_GET_TOKEN'
// popup param mutations
export const POPUP_SET_PARAM = 'POPUP_SET_PARAM'
export const POPUP_SET_RETVALUE = 'POPUP_SET_RETVALUE'
export const HELP_SET_PARAM = 'HELP_SET_PARAM'
export const HELP_SET_RETVALUE = 'HELP_SET_RETVALUE'

// 地震保険の調査情報（加入率）
export const EARTHQUAKE_SET_SYNC = 'EARTHQUAKE_SET_SYNC'
export const EARTHQUAKE_SET_SUBSCRIBER = 'EARTHQUAKE_SET_SUBSCRIBER'
export const EARTHQUAKE_SET_CONTRACTDOCUMENTS = 'EARTHQUAKE_SET_CONTRACTDOCUMENTS'

// Loading mutations
export const UI_SET_LOADING_ON = 'UI_SET_LOADING_ON'
export const UI_SET_LOADING_OFF = 'UI_SET_LOADING_OFF'

// エラーダイアログ
export const API_ERROR = 'API_ERROR'
export const API_CLEAR_ERROR = 'API_CLEAR_ERROR'

// マイページAPI
export const MYPAGE_SET_SYNC = 'MYPAGE_SET_SYNC'
export const MYPAGE_SET_USER_PROFILE = 'MYPAGE_SET_USER_PROFILE'

// 明記物件明細書入力画面の入力完了
export const MYAPP_SPECIFICATION_ARTICLE_INPUT_INIT = 'MYAPP_SPECIFICATION_ARTICLE_INPUT_INIT'
export const MYAPP_SPECIFICATION_ARTICLE_INPUT_COMPLETED = 'MYAPP_SPECIFICATION_ARTICLE_INPUT_COMPLETED'
export const SET_SPECIFICATION_ARTICLE_INPUT_CHANGE_FLAG = 'SET_SPECIFICATION_ARTICLE_INPUT_CHANGE_FLAG'
// 他契約有無確認画面
export const MYAPP_WITH_OTHER_INIT = 'MYAPP_WITH_OTHER_INIT'
export const MYAPP_WITH_OTHER_CONFIRM = 'MYAPP_WITH_OTHER_CONFIRM'
export const SET_CONFIRM_TERM_CLEAR_FLAG = 'SET_CONFIRM_TERM_CLEAR_FLAG'

// 代理店分担入力画面
export const MYAPP_AGENT_SHARE_INPUT_COMPLETED = 'MYAPP_AGENT_SHARE_INPUT_COMPLETED'
export const MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST = 'MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST'
export const MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST_NEW = 'MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST_NEW'
export const MANAGEMENT_GETAGENTNAME = 'MANAGEMENT_GETAGENTNAME'
export const MYAPP_AGENT_SHARE_INPUT_SET_TEMP_DATA = 'MYAPP_AGENT_SHARE_INPUT_SET_TEMP_DATA'

// 各種資料アップロード画面
export const MYAPP_SET_SENDFLAGDATA = 'MYAPP_SET_SENDFLAGDATA'

// 申込依頼画面（口振）
export const MYAPP_ENTRYACCOUNTTRANSFER_GET_API = 'MYAPP_ENTRYACCOUNTTRANSFER_GET_API'
export const MYAPP_ENTRYACCOUNTTRANSFER_GET_API_TEMP = 'MYAPP_ENTRYACCOUNTTRANSFER_GET_API_TEMP'

// G-NHA-010_内容確認画面
export const MYAPP_SEARCH_RECRUITMENT = 'MYAPP_SEARCH_RECRUITMENT'
export const MYAPP_SET_RECRUITMENT_ID = 'MYAPP_SET_RECRUITMENT_ID'

// 有料オプション設定ポップアップ画面（ホームアシスト）
export const MYAPP_ESTIMATE_OPTION_INIT = 'MYAPP_ESTIMATE_OPTION_INIT'

// 口座検索
export const MYAPP_BANK_SEARCH_OK = 'MYAPP_BANK_SEARCH_OK'
export const MYAPP_BANK_SEARCH_ERROR = 'MYAPP_BANK_SEARCH_ERROR'
export const MYAPP_BANK_SET = 'MYAPP_BANK_SET'

// 代理店分担入力
export const MYAPP_AGENT_SHARE_INPUT_INIT = 'MYAPP_AGENT_SHARE_INPUT_INIT'
// 印刷書作成フラグ
export const MYAPP_BANK_PRINT_FLAG = 'MYAPP_BANK_PRINT_FLAG'
// EntryInfo 確認
export const MYAPP_ENTRYCREDITCARDCONFIRMED = 'MYAPP_ENTRYCREDITCARDCONFIRMED'
// メール確認画面
export const MYAPP_SET_AGENT_CODE = 'MYAPP_SET_AGENT_CODE'

// 一時保存（契約者名）
export const MYAPP_CONTRACTORNAME = 'MYAPP_CONTRACTORNAME'

export const MUTATIONS = {
  // config
  CONFIGS_INIT,
  CONFIGS_DIRECT_RESET,
  CONFIGS_ACTION_RESET,
  CONFIGS_CHANGE_MOBILE,
  CONFIGS_SET_COOKIE,
  READ_NOTICE_LIST,
  READ_ENTRY_NO_LIST,
  CLEAR_ENTRY_NO_LIST,
  // 見積連番一覧
  MYAPP_READ_ENTRY_NO_LIST,
  MYAPP_SET_ENTRY_NO,
  // TOP画面の見積連番一覧POP
  UI_SET_TOP_MITUMORI,

  // ui mutations
  UI_SET_POPUP,
  UI_SET_CONFIRM_IN_POPUP_CLOSE,
  UI_SET_HELP,
  UI_SET_DOCUMENT,

  // errors mutations
  ERROR_UI_SET_POPUP,
  ERROR_UI_SET_POPUP_CONFIRM,
  ERROR_UI_UNSET_POPUP_CONFIRM,

  // home assist
  MYAPP_SET_SYNC,
  MYAPP_SET_ENTRY_TYPE,
  MYAPP_SET_POLICY_NO,
  MYAPP_SET_DATA,
  MYAPP_SET_BEFORE_CORRECTION,
  MYAPP_SET_DATA_APPRAISAL,
  MYAPP_SET_UPLOAD_FILE_INFO,
  MYAPP_SET_ALERT_INFO,
  MYAPP_SET_ESTIMATEDDATA,
  MYAPP_SET_ADDRESSDATA,
  MYAPP_CLEAR_DATA,
  // 評価法
  MYAPP_SVR_ACQUISITION_ANNUAL,
  MYAPP_SVR_OVERVIEW,
  // 家財評価額算出
  MYAPP_SVR_HOUSEHOLD_EVOLUTION,
  // 試算結果
  MYAPP_SET_ESTIMATE,
  // 引受制限
  MYAPP_SVR_ACCEPT_LIMIT_RULE_ADD,
  MYAPP_SVR_ACCEPT_LIMIT_RULE_REMOVE,
  MYAPP_SVR_ACCEPT_LIMIT_CHECK,
  MYAPP_SVR_ACCEPT_LIMIT_CACHE_CLEAR,
  MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_SAVE,
  MYAPP_SVR_ACCEPT_LIMIT_CONFIRM_CODE_CLEAR,

  MYAPP_SET_SHOW_AGENTSHAREINPUT,
  // SMBC
  SMBC_GET_TOKEN,
  // popup param
  POPUP_SET_PARAM,
  POPUP_SET_RETVALUE,
  HELP_SET_PARAM,
  HELP_SET_RETVALUE,

  // 地震保険の調査情報（加入率）
  EARTHQUAKE_SET_SYNC,
  EARTHQUAKE_SET_SUBSCRIBER,
  EARTHQUAKE_SET_CONTRACTDOCUMENTS,
  // Loading
  UI_SET_LOADING_OFF,
  UI_SET_LOADING_ON,
  // API
  API_ERROR,
  API_CLEAR_ERROR,

  // マイページAPI
  MYPAGE_SET_SYNC,
  MYPAGE_SET_USER_PROFILE,

  // 明記物件明細書入力画面
  MYAPP_SPECIFICATION_ARTICLE_INPUT_INIT,
  MYAPP_SPECIFICATION_ARTICLE_INPUT_COMPLETED,
  SET_SPECIFICATION_ARTICLE_INPUT_CHANGE_FLAG,
  // 他契約有無確認画面
  MYAPP_WITH_OTHER_INIT,
  MYAPP_WITH_OTHER_CONFIRM,
  SET_CONFIRM_TERM_CLEAR_FLAG,

  // 代理店分担入力画面
  MYAPP_AGENT_SHARE_INPUT_COMPLETED,
  MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST,
  MYAPP_AGENT_SHARE_INPUT_GET_AGENTCD_LIST_NEW,
  MANAGEMENT_GETAGENTNAME,
  MYAPP_AGENT_SHARE_INPUT_SET_TEMP_DATA,

  // 各種資料アップロード画面
  MYAPP_SET_SENDFLAGDATA,

  // 申込依頼画面（口振）
  MYAPP_ENTRYACCOUNTTRANSFER_GET_API,
  MYAPP_ENTRYACCOUNTTRANSFER_GET_API_TEMP,

  // G-NHA-010_内容確認画面
  MYAPP_SEARCH_RECRUITMENT,
  MYAPP_SET_RECRUITMENT_ID,

  // 有料オプション設定ポップアップ画面（ホームアシスト）
  MYAPP_ESTIMATE_OPTION_INIT,
  // 口座検索
  MYAPP_BANK_SEARCH_OK,
  MYAPP_BANK_SEARCH_ERROR,
  MYAPP_BANK_SET,
  // 代理店分担入力
  MYAPP_AGENT_SHARE_INPUT_INIT,
  // 銀行印刷書作成フラグ
  MYAPP_BANK_PRINT_FLAG,
  MYAPP_ENTRYCREDITCARDCONFIRMED,
  // 代理店コード設定
  MYAPP_SET_AGENT_CODE,
  // 一時保存（契約者名）
  MYAPP_CONTRACTORNAME
}
